version: "3"
services:
  localstack:
    image: localstack/localstack
    container_name: "localstack"
    network_mode: bridge
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=eu-west-1
      - EDGE_PORT=4566
      - DEBUG=1
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
